spring:
  application:
    name: ms-app1

  #mq 접속정보   
  rabbitmq:
    host: "192.168.56.20" #${mq_host:192.168.56.20}
    port: "5672" #${mq_port:15672}
    username: guest #${mq_id:guest}
    password: guest #${mq_pw:guest}


ms-app1:
  profile: I'm local ms-app1.updated3
  comment: Hello! local ms-app1.updated3