spring:
  config:
    activate:
      on-profile: local

taeng:
  profile: I'm local taeng
  comment: Hello! local taeng

---
spring:
  config:
    activate:
      on-profile: dev

taeng:
  profile: I'm dev taeng. updated3!!
  comment: Hello! dev taeng updated3!!

---
spring:
  config:
    activate:
      on-profile: prod

taeng:
  profile: I'm prod taeng
  comment: Hello! prod taeng