##########################################
## spiring cloud gateway서버의 라이팅 설정 정보
#########################################
spring:
  cloud:
    gateway:
      
#      discovery:
#        locator:
#          enabled: true  #Eureka연동하여 호출할 서비스주소를 가져오겠다는 뜻 (근대 주석처리해도 //lb로 잘호울된다.)
      routes:
        - id: ms-app1  #단순히 라우팅을 식별하는 아이디
          uri: lb://ms-app1   #호출되는앱주소(Eureka연동시 로드밸런서를 통해 호출), 직접url 호출시 'http://localhost:8081/'
          predicates: #조건
            - Path=/ms-app1/**   #라우팅동작조건: 요청이 'gw주소/ms-app1/dynamic' 이렇게 들어오는 경우 해당 라우팅이 처리한다
          filters: #필터처리(생략가능, 여러개의 필터를 붙일수 있다.)
            - RewritePath=/ms-app1/(?<path>.*),/$\{path}  #RewritePath필터 : gw에 들어온 uri경로를 변경하여 라우팅 대상을 호출하겠다는의미. 형식 'RewritePath=변경전패스,변경후패스'  
              #만일 gw 요청 uri path에 '/ms-app1' 들어있으면 '/ms-app1'부분 제거하여 라우팅 하겠다는 의미  'http://localhost:9021/ms-app1/dynamic' --> 'http://localhost:8081/dynamic' 한다는의미    
              #만일 filters.RewritePath 속성이 없으면 paht는 그대로라우팅  'http://localhost:9021/ms-app1/dynamic' --> 'http://localhost:8081/ms-app1/dynamic'
            
        - id: ms-app2
          uri: lb://ms-app2
          predicates:
            - Path=/ms-app2/**
          filters:
            - RewritePath=/ms-app2/(?<path>.*),/$\{path}  
  
#logging:
#  level:
#    root: 'debug'  